# models/staging/sources.yml
version: 2

sources:
  - name: raw_data
    database: dev
    schema: raw_data
    tables:
      - name: market_data
        description: "Raw stock market data loaded from API"
        columns:
          - name: stock
            description: "Stock symbol"
            tests:
              - not_null
          - name: open
            description: "Opening price"
            tests:
              - not_null
          - name: high
            description: "Highest price"
            tests:
              - not_null
          - name: low
            description: "Lowest price"
            tests:
              - not_null
          - name: close
            description: "Closing price"
            tests:
              - not_null
          - name: volume
            description: "Trading volume"
            tests:
              - not_null
          - name: date
            description: "Trading date"
            tests:
              - not_null
